# Generated by Django 5.1.6 on 2026-03-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('agriculture', 'Agriculture Farm'), ('plot', 'Plot'), ('flat', 'Flat'), ('rent', 'Rent')], max_length=30),
        ),
    ]
