# Generated by Django 5.1.6 on 2026-03-24 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('ec', 'Encumbrance Certificate (EC)'), ('mother_deed', 'Mother Deed'), ('khata', 'Khata Certificate'), ('rtc', 'RTC (Pahani)'), ('conversion_order', 'Conversion Order'), ('sale_deed', 'Sale Deed'), ('rera_cert', 'RERA Certificate'), ('tax_receipt', 'Property Tax Receipt'), ('plan_approval', 'Building Plan Approval'), ('other', 'Other')], max_length=30)),
                ('s3_key', models.CharField(max_length=500)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('checksum', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
